config/routes.rb
AddisFarmMarket::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
root :to => 'static_pages#welcome'
  resources :mushrooms do
    resources :mushroom_orders
  end

 resources :milks do
    resources :milk_orders
  end

  resources :honeys do
    resources :honey_orders
  end

  resources :eggs do
    resources :egg_orders
  end

  

end

app/models/mushroom.rb
class Mushroom < ActiveRecord::Base
  validates_presence_of :location, :message => "can't be blank"
  validates_presence_of :quantity, :message => "can't be blank"
  validates_presence_of :price, :message => "can't be blank"
  validates_presence_of :reciept, :message => "can't be blank"
  validates_presence_of :day_of_supply, :message => "can't be blank"
  validate :supply_could_not_be_less_than_zero

  has_many :mushroom_orders
  belongs_to :user
  private
    def supply_could_not_be_less_than_zero
      errors.add(:quantity, "should not be less than zero") if quantity < 1
    end
  end
end

app/controllers/mushrooms_controller.rb
class MushroomsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  load_and_authorize_resource
  before_action :set_mushroom, only: [:show, :edit, :update, :destroy]

  # GET /mushrooms
  # GET /mushrooms.json
  def index
    @mushrooms = Mushroom.all
  end

  # GET /mushrooms/1
  # GET /mushrooms/1.json
  def show
  end

  # GET /mushrooms/new
  def new
    @mushroom = Mushroom.new
  end

  # GET /mushrooms/1/edit
  def edit
  end

  # POST /mushrooms
  # POST /mushrooms.json
  def create
    @mushroom = Mushroom.new(mushroom_params)
    @mushroom.user = current_user
    @mushroom.company = current_user.company_name
    


    respond_to do |format|
      if @mushroom.save
        format.html { redirect_to @mushroom, notice: 'Mushroom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mushroom }
      else
        format.html { render action: 'new' }
        format.json { render json: @mushroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mushrooms/1
  # PATCH/PUT /mushrooms/1.json
  def update
    respond_to do |format|
      if @mushroom.update(mushroom_params)
        format.html { redirect_to @mushroom, notice: 'Mushroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mushroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mushrooms/1
  # DELETE /mushrooms/1.json
  def destroy
    @mushroom.destroy
    respond_to do |format|
      format.html { redirect_to mushrooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mushroom
      @mushroom = Mushroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mushroom_params
      params.require(:mushroom).permit(:user_id, :company, :location, :day_of_supply, :quantity, :price, :reciept)
    end
end

app/helpers/mushrooms_helper.rb
module MushroomsHelper
end

app/views/mushrooms/_form.html.erb
<%= form_for(@mushroom) do |f| %>
  <% if @mushroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mushroom.errors.count, "error") %> prohibited this mushroom from being saved:</h2>

      <ul>
      <% @mushroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :company %>
  </div>
 <div class="field">
    <%= f.label :location %>
    <%= f.select :location, options_for_select(%w[Bole Yeka Kirkos Arada Gulele Nifas_Silk_Lafto Addis_Ketema Akaki Ledeta Lafto]) %>
  </div>
   <div class="field">
    <%= f.label :reciept %>
    <%= f.select :reciept, options_for_select(%w[VAT TOT None]) %>
  </div>
  <div class="field">
    <%= f.label :day_of_supply %><br>
    <%= f.datetime_select :day_of_supply %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mushrooms/edit.html.erb
<h1>Editing mushroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @mushroom %> |
<%= link_to 'Back', mushrooms_path %>

app/views/mushrooms/index.html.erb
<h1>Listing mushrooms</h1>

<table>
  <thead>
    <tr>
     
      <th>Company</th>
      <th>Location</th>
      <th>Day of supply</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Reciept</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mushrooms.each do |mushroom| %>
      <tr>
        
        <td><%= mushroom.company %></td>
        <td><%= mushroom.location %></td>
        <td><%= mushroom.day_of_supply %></td>
        <td><%= mushroom.quantity %></td>
        <td><%= number_to_currency(mushroom.price) %></td>
        <td><%= mushroom.reciept %></td>
        <td><%= link_to raw("<i class='pull-right icon-chevron-right'></i> #{mushroom.mushroom_orders.count}#{"Orders"} "),mushroom_mushroom_orders_path(mushroom)  %></td>
        <td>
          <% if can? :update, mushroom %>
          <%= link_to 'Edit', edit_mushroom_path(mushroom) %>
          <% end %>
        </td>
        <td>
          <% if can? :delete, mushroom %>
          <%= link_to 'Destroy', mushroom, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Mushroom %>
<%= link_to 'New Mushroom', new_mushroom_path %>
<% end %>

app/views/mushrooms/new.html.erb
<h1>New mushroom</h1>

<%= render 'form' %>

<%= link_to 'Back', mushrooms_path %>

app/views/mushrooms/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Company:</strong>
  <%= @mushroom.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @mushroom.location %>
</p>

<p>
  <strong>Day of supply:</strong>
  <%= @mushroom.day_of_supply %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @mushroom.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@mushroom.price) %>
</p>

<p>
  <strong>Reciept:</strong>
  <%= @mushroom.reciept %>
</p>

<%= link_to 'Edit', edit_mushroom_path(@mushroom) %> |
<%= link_to 'Back', mushrooms_path %>