config/routes.rb
AddisFarmMarket::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
root :to => 'static_pages#welcome'
  resources :mushrooms do
    resources :mushroom_orders
  end

 resources :milks do
    resources :milk_orders
  end

  resources :honeys do
    resources :honey_orders
  end

  resources :eggs do
    resources :egg_orders
  end

  

end

app/models/mushroom_order.rb
class MushroomOrder < ActiveRecord::Base
  validates_presence_of :location, :message => "can't be blank"
  validates_presence_of :quantity, :message => "can't be blank"
  validates_presence_of :price, :message => "can't be blank"
  validate :quantity_is_less_than_supply
  validate :price_must_be_more

  belongs_to :mushroom
  belongs_to :user
  

  private
   def price_must_be_more
    errors.add(:price, "should be more than offer") if price < mushroom.price
   end

   def quantity_is_less_than_supply
    errors.add(:quantity, "should be less than supply") if quantity > mushroom.quantity
   end
end

app/controllers/mushroom_orders_controller.rb
class MushroomOrdersController < ApplicationController
 before_filter :authenticate_user!, :except => [:index]
 load_and_authorize_resource
 before_action :set_mushroom_order, only: [:show, :edit, :update, :destroy]

  # GET /posts/:post_id/comments
  # GET /posts/:post_id/comments.xml
  def index
    #1st you retrieve the post thanks to params[:post_id]
    @mushroom = Mushroom.find(params[:mushroom_id])
    #2nd you get all the comments of this post
    @mushroom_orders = @mushroom.mushroom_orders 
 
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mushroom_orders }
    end
  end
 
  # GET /posts/:post_id/comments/:id
  # GET /comments/:id.xml
  def show
    #1st you retrieve the post thanks to params[:post_id]
    mushroom = Mushroom.find(params[:mushroom_id])
    #2nd you retrieve the comment thanks to params[:id]
    @mushroom_order = mushroom.mushroom_orders.find(params[:id])
     
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mushroom_order }
    end
  end
 
  # GET /posts/:post_id/comments/new
  # GET /posts/:post_id/comments/new.xml
  def new
    #1st you retrieve the post thanks to params[:post_id]
    mushroom = Mushroom.find(params[:mushroom_id])
    #2nd you build a new one
    @mushroom_order = mushroom.mushroom_orders.build
 
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mushroom_order }
    end
  end
 
  # GET /posts/:post_id/comments/:id/edit
  def edit
    #1st you retrieve the post thanks to params[:post_id]
    mushroom = Mushroom.find(params[:mushroom_id])
    #2nd you retrieve the comment thanks to params[:id]
    @mushroom_order = mushroom.mushroom_orders.find(params[:id])
  end
 
  # POST /posts/:post_id/comments
  # POST /posts/:post_id/comments.xml
  def create
    #1st you retrieve the post thanks to params[:post_id]
    mushroom = Mushroom.find(params[:mushroom_id])
    #2nd you create the comment with arguments in params[:comment]
    @mushroom_order = mushroom.mushroom_orders.create(mushroom_order_params)
    @mushroom_order.user = current_user
    @mushroom_order.company = current_user.company_name
    

  

    respond_to do |format|
      if @mushroom_order.save
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to([@mushroom_order.mushroom, @Mushroomorder], :notice => 'An Mushroom order was successfully created.') }
        #the key :location is associated to an array in order to build the correct route to the nested resource comment
        format.xml  { render :xml => @mushroom_order, :status => :created, :location => [@Mushroomorder.mushroom, @Mushroomorder] }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mushroom_order.errors, :status => :unprocessable_entity }
      end
    end
  end
 
  # PUT /posts/:post_id/comments/:id
  # PUT /posts/:post_id/comments/:id.xml
  def update
    #1st you retrieve the post thanks to params[:post_id]
    @mushroom = Mushroom.find(params[:mushroom_id])
    #2nd you retrieve the comment thanks to params[:id]
    @mushroom_order = @mushroom.mushroom_orders.find(params[:id])
    if @mushroom_order.accepted == TRUE and current_user.role == "seller" 
         @mushroom.quantity = (@mushroom.quantity + @mushroom_order.quantity)
       elsif current_user.role == "seller"
          @mushroom.quantity = (@mushroom.quantity - @mushroom_order.quantity)
      end
      @mushroom.save
 
    respond_to do |format|
      if @mushroom_order.update_attributes(mushroom_order_params)
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to ([@mushroom_order.mushroom,@mushroom_order]), :notice => 'Mushroom order was successfully updated.' }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mushroom_order.errors, :status => :unprocessable_entity }
      end
    end
  end
 
  # DELETE /posts/:post_id/comments/1
  # DELETE /posts/:post_id/comments/1.xml
  def destroy
    #1st you retrieve the post thanks to params[:post_id]
    mushroom = Mushroom.find(params[:Mushroom_id])
    #2nd you retrieve the comment thanks to params[:id]
    @Mushroomorder = mushroom.mushroom_order.find(params[:id])
    @Mushroomorder.destroy
 
    respond_to do |format|
      #1st argument reference the path /posts/:post_id/comments/
      format.html { redirect_to(Mushroom_Mushroomorders_url) }
      format.xml  { head :ok }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mushroom_order
      @Mushroom_order = MushroomOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mushroom_order_params
      params.require(:mushroom_order).permit(:user_id, :company, :tel, :location, :quantity, :price, :accepted)
    end
  end

app/helpers/mushroom_orders_helper.rb
module MushroomOrdersHelper
end

app/views/mushroom_orders/_form.html.erb
<%= form_for([@mushroom_order.mushroom, @mushroom_order]) do |f| %>
  <% if @mushroom_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mushroom_order.errors.count, "error") %> prohibited this mushroom_order from being saved:</h2>

      <ul>
      <% @mushroom_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :mushroom_id %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :company %>
  </div>
 <div class="field">
    <%= f.label :location %>
    <%= f.select :location, options_for_select(%w[Bole Yeka Kirkos Arada Gulele Nifas_Silk_Lafto Addis_Ketema Akaki Ledeta Lafto]) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mushroom_orders/_index.html.erb
<table>
  <thead>
    <tr>
     
      <th>Company</th>
      <th>Location</th>
      <th>Day of supply</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Reciept</th>
     
    </tr>
  </thead>

  <tbody>
   
      <tr>
        
        <td><%= @mushroom.company %></td>
        <td><%= @mushroom.location %></td>
        <td><%= @mushroom.day_of_supply %></td>
        <td><%= @mushroom.quantity %></td>
        <td><%= number_to_currency(@mushroom.price) %></td>
        <td><%= @mushroom.reciept %></td>
      </tr>
    </tbody>
  </table>

app/views/mushroom_orders/edit.html.erb
<h1>Editing mushroom_order</h1>

<%= render 'form' %>

<%= link_to 'Show', [@mushroom_order.mushroom, @mushroom_order] %> |
<%= link_to 'Back',mushroom_mushroom_orders_path(@mushroom_order.mushroom) %>

app/views/mushroom_orders/index.html.erb
<div class = "adjust">
  <%= render 'index' %>
</div>
<h1>Listing mushroom_orders</h1>

<table>
  <thead>
    <tr>
      
      
      <th>Company</th>
      <th>Location</th>
      <th>Quantity</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mushroom_orders.each do |mushroom_order| %>
      <tr>
        
        <td><%= mushroom_order.company %></td>
        <td><%= mushroom_order.location %></td>
        <td><%= mushroom_order.quantity %></td>
        <td><%= number_to_currency(mushroom_order.price) %></td>
         <% @mushroom_ordered = mushroom_order %>
        <% if can? :update, @mushroom_ordered and current_user.role == "seller"  %>
        <td><span style='font-size: 1.75em;'><%= best_in_place [@mushroom_ordered.mushroom,@mushroom_ordered], :accepted, :type => :checkbox, 
          :collection => [raw("<i class='icon-check-empty'></i>"), raw("<i class='icon-check'></i>")] %></span></td>
        <% elsif current_user.role == "seller" %>
        <td class="blank"></td>
        <% end %>
        <td>
          <% if can? :update, mushroom_order  and current_user.role == "buyer" %>
          <%= link_to 'Edit', edit_mushroom_mushroom_order_path(mushroom_order.mushroom, mushroom_order) %>
          <% end %>
        </td>
        <td>
          <% if can? :delete, mushroom_order %>
          <%= link_to 'Destroy', [mushroom_order.mushroom, mushroom_order], method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, MushroomOrder %>
 <%= link_to 'New Mushroom order', new_mushroom_mushroom_order_path %>
 <% end %>
 <%= link_to 'Back', mushrooms_path %>

app/views/mushroom_orders/new.html.erb
<h1>New mushroom_order</h1>

<%= render 'form' %>

<%= link_to 'Back', mushroom_mushroom_orders_path(@mushroom_order.mushroom) %>

app/views/mushroom_orders/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Company:</strong>
  <%= @mushroom_order.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @mushroom_order.location %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @mushroom_order.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@mushroom_order.price) %>
</p>

<%= link_to 'Edit', edit_mushroom_mushroom_order_path(@mushroom_order.mushroom, @mushroom_order) %> |
<%= link_to 'Back', mushroom_mushroom_orders_path(@mushroom_order.mushroom) %>