config/routes.rb
AddisFarmMarket::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
root :to => 'static_pages#welcome'
  resources :mushrooms do
    resources :mushroom_orders
  end

 resources :milks do
    resources :milk_orders
  end

  resources :honeys do
    resources :honey_orders
  end

  resources :eggs do
    resources :egg_orders
  end

  

end

app/models/egg.rb
class Egg < ActiveRecord::Base
  
  validates_presence_of :location, :message => "can't be blank"
  validates_presence_of :type_of_egg, :message => "can't be blank"
  validates_presence_of :daily_quantity, :message => "can't be blank"
  validates_presence_of :price, :message => "can't be blank"
  validates_presence_of :reciept, :message => "can't be blank"
  validate :supply_could_not_be_less_than_zero

  has_many :egg_orders
  belongs_to :user
  private
    def supply_could_not_be_less_than_zero
      errors.add(:daily_quantity, "should not be less than zero") if daily_quantity < 1
    end
  end

app/controllers/eggs_controller.rb
class EggsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  load_and_authorize_resource 
  before_action :set_egg, only: [:show, :edit, :update, :destroy]

  # GET /eggs
  # GET /eggs.json
  def index
    @eggs = Egg.all
    
  end

  # GET /eggs/1
  # GET /eggs/1.json
  def show
  end

  # GET /eggs/new
  def new
    @egg = Egg.new
  end

  # GET /eggs/1/edit
  def edit
  end

  # POST /eggs
  # POST /eggs.json
  def create
    @egg = Egg.new(egg_params)
    @egg.user = current_user
    @egg.company = current_user.company_name
    




    respond_to do |format|
      if @egg.save
        format.html { redirect_to @egg, notice: 'Egg was successfully created.' }
        format.json { render action: 'show', status: :created, location: @egg }
      else
        format.html { render action: 'new' }
        format.json { render json: @egg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eggs/1
  # PATCH/PUT /eggs/1.json
  def update
    
    respond_to do |format|
      if @egg.update(egg_params)
        format.html { redirect_to eggs_url, notice: 'Egg was successfully updated.' }
        format.json { respond_with_bip(@egg) }
      else
        format.html { render action: 'edit' }
        format.json { render json: @egg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eggs/1
  # DELETE /eggs/1.json
  def destroy
    @egg.destroy
    respond_to do |format|
      format.html { redirect_to eggs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_egg
      @egg = Egg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def egg_params
      params.require(:egg).permit(:user_id, :company, :location, :type_of_egg, :daily_quantity,  :price, :reciept)
    end
end

app/helpers/eggs_helper.rb
module EggsHelper

end

app/views/eggs/_form.html.erb
<%= form_for(@egg) do |f| %>
  <% if @egg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@egg.errors.count, "error") %> prohibited this egg from being saved:</h2>

      <ul>
      <% @egg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :company %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.select :location, options_for_select(%w[Bole Yeka Kirkos Arada Gulele Nifas_Silk_Lafto Addis_Ketema Akaki Ledeta Lafto]) %>
  </div>
  <div class="field">
    <%= f.label :type_of_egg %>
    <%= f.select :type_of_egg, options_for_select(%w[Habesha Ferenj]) %>
  </div>
  <div class="field">
    <%= f.label :reciept %>
    <%= f.select :reciept, options_for_select(%w[VAT TOT None]) %>
  </div>
  <div class="field">
    <%= f.label "Daily Supply" %>
    <%= f.number_field :daily_quantity %>
  </div>
  <div class="field">
    <%= f.label "Unit Price" %>
    <%= f.text_field :price, :placeholder => "0.00" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eggs/edit.html.erb
<h1>Editing egg</h1>

<%= render 'form' %>

<%= link_to 'Show', @egg %> |
<%= link_to 'Back', eggs_path %>

app/views/eggs/index.html.erb
<h1>Egg Market</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      
      <th>Company</th>
      <th>Location</th>
      <th>Type of egg</th>
      <th>Daily quantity</th>
      <th>Price</th>
      <th>Reciept</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @eggs.each do |egg| %>
      <tr class="row_class">
        
        <td><%= egg.company %></td>
        <td><%= egg.location %></td>
        <td><%= egg.type_of_egg %></td>
        <td><%= best_in_place egg, :daily_quantity %></td>
        <td><%= number_to_currency(egg.price) %></td>
        <td><%= egg.reciept %></td>
        <td class="btn btn-mini"> <%= link_to raw("<i class='pull-right icon-hand-up'></i>#{egg.egg_orders.count}#{"Orders"} "),egg_egg_orders_path(egg)  %></td>
           <td>
          
         <% if can? :update, egg %>
          <%= link_to 'Edit', edit_egg_path(egg) %>
          <% end %>
        </td>
        <td>
          <% if can? :delete, egg %>
          <%= link_to 'Destroy', egg, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Egg %>
<%= link_to 'New Egg', new_egg_path %>
<% end %>

app/views/eggs/new.html.erb
<h1>New egg</h1>

<%= render 'form' %>

<%= link_to 'Back', eggs_path %>

app/views/eggs/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered table-condensed table-hover">
  <thead>
    <td><strong>Company</strong></td>
    <td><strong>Location</strong></td>
    <td><strong>Egg Type</strong></td>
    <td><strong>Daily Quantity</strong></td>
    <td><strong>Price Per Egg</strong></td>
    <td><strong>Reciept</strong></td>
  </thead>
  <tbody>

  <td><%= @egg.company %></td>

  <td><%= @egg.location %></td>

  <td><%= @egg.type_of_egg %></td>

  <td><%= @egg.daily_quantity %></td>

  <td><%= number_to_currency(@egg.price) %></td>

  <td><%= @egg.reciept %></td>
</tbody>
</table>
<%= link_to 'Put this on Market', eggs_path,:class => "btn btn-large btn-primary" %>
<%= link_to 'Edit', edit_egg_path(@egg),:class => "btn btn-large btn-warning" %></td>