config/routes.rb
AddisFarmMarket::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
root :to => 'static_pages#welcome'
  resources :mushrooms do
    resources :mushroom_orders
  end

 resources :milks do
    resources :milk_orders
  end

  resources :honeys do
    resources :honey_orders
  end

  resources :eggs do
    resources :egg_orders
  end

  

end

app/models/milk.rb
class Milk < ActiveRecord::Base
  validates_presence_of :location, :message => "can't be blank"
  validates_presence_of :daily_quantity, :message => "can't be blank"
  validates_presence_of :price, :message => "can't be blank"
  validates_presence_of :reciept, :message => "can't be blank"
  validates_presence_of :condition, :message => "can't be blank"
  validate :supply_could_not_be_less_than_zero

  has_many :milk_orders
  belongs_to :user
   private
    def supply_could_not_be_less_than_zero
      errors.add(:daily_quantity, "should not be less than zero") if daily_quantity < 1
    end
  end
end

app/controllers/milks_controller.rb
class MilksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  load_and_authorize_resource
  before_action :set_milk, only: [:show, :edit, :update, :destroy]

  # GET /milks
  # GET /milks.json
  def index
    @milks = Milk.all
  end

  # GET /milks/1
  # GET /milks/1.json
  def show
  end

  # GET /milks/new
  def new
    @milk = Milk.new
  end

  # GET /milks/1/edit
  def edit
  end

  # POST /milks
  # POST /milks.json
  def create
    @milk = Milk.new(milk_params)
    @milk.user = current_user
    @milk.company = current_user.company_name
    

    respond_to do |format|
      if @milk.save
        format.html { redirect_to @milk, notice: 'Milk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @milk }
      else
        format.html { render action: 'new' }
        format.json { render json: @milk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milks/1
  # PATCH/PUT /milks/1.json
  def update
    respond_to do |format|
      if @milk.update(milk_params)
        format.html { redirect_to @milk, notice: 'Milk was successfully updated.' }
        format.json { respond_with_bip @milk }
      else
        format.html { render action: 'edit' }
        format.json { render json: @milk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milks/1
  # DELETE /milks/1.json
  def destroy
    @milk.destroy
    respond_to do |format|
      format.html { redirect_to milks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milk
      @milk = Milk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milk_params
      params.require(:milk).permit(:user, :company, :tel, :location, :condition, :price, :reciept, :daily_quantity)
    end
end

app/helpers/milks_helper.rb
module MilksHelper
end

app/views/milks/_form.html.erb
<%= form_for(@milk) do |f| %>
  <% if @milk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milk.errors.count, "error") %> prohibited this milk from being saved:</h2>

      <ul>
      <% @milk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :company %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.select :location, options_for_select(%w[Bole Yeka Kirkos Arada Gulele Nifas_Silk_Lafto Addis_Ketema Akaki Ledeta Lafto]) %>
  </div>
   <div class="field">
    <%= f.label :condition %>
    <%= f.select :condition, options_for_select(%w[Packed Unpacked]) %>
  </div>
  <div class="field">
    <%= f.label :reciept %>
    <%= f.select :reciept, options_for_select(%w[VAT TOT None]) %>
  </div>
  <div class="field">
    <%= f.label :daily_quantity %><br>
    <%= f.number_field :daily_quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/milks/edit.html.erb
<h1>Editing milk</h1>

<%= render 'form' %>

<%= link_to 'Show', @milk %> |
<%= link_to 'Back', milks_path %>

app/views/milks/index.html.erb
<h1>Listing milks</h1>

<table>
  <thead>
    <tr>
      
      <th>Company</th>
      <th>Location</th>
      <th>Daily quantity</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Reciept</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @milks.each do |milk| %>
      <tr>
        
        <td><%= milk.company %></td>
        <td><%= milk.location %></td>
        <td><%= milk.daily_quantity %></td>
        <td><%= milk.condition %></td>
        <td><%= number_to_currency(milk.price) %></td>
        <td><%= milk.reciept %></td>
         <td> <%= link_to raw("<i class='pull-right icon-chevron-right'></i> #{milk.milk_orders.count}#{"Orders"} "),milk_milk_orders_path(milk)  %></td>
        <td>
          <% if can? :update, milk %>
          <%= link_to 'Edit', edit_milk_path(milk) %>
          <% end %>
        </td>
        <td>
          <% if can? :delete, milk %>
          <%= link_to 'Destroy', milk, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Milk %>
<%= link_to 'New Milk', new_milk_path %>
<% end %>

app/views/milks/new.html.erb
<h1>New milk</h1>

<%= render 'form' %>

<%= link_to 'Back', milks_path %>

app/views/milks/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Company:</strong>
  <%= @milk.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @milk.location %>
</p>

<p>
  <strong>Daily quantity:</strong>
  <%= @milk.daily_quantity %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @milk.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@milk.price) %>
</p>

<p>
  <strong>Reciept:</strong>
  <%= @milk.reciept %>
</p>

<%= link_to 'Edit', edit_milk_path(@milk) %> |
<%= link_to 'Back', milks_path %>